blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/ashfromsky/helix/wiki
    about: Check the docs first
  - name: ðŸ’¬ Discussions
    url: https://github.com/ashfromsky/helix/discussions
    about: Ask questions and discuss ideas